name: github-actions-init
on: [push]
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
            python-version: '3.8'
      - run: python3 --version
